pipeline {
    agent any
    stages {
        stage('Create folder') {
            steps {
                sh 'mkdir /home/traych/jenkins'
            }
        }
        stage('Create file') {
            steps {
                sh 'touch /home/traych/jenkins/jenkins.txt'
            }
        }
    }
}
